version: "3.8"

services:
  node-server:
    build:
      context: ./node-server
    ports:
      - "4000:4000"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BROKER=kafka:9092
      - PORT=4000
    networks:
      - kafka-network

  react-client:
    build:
      context: ./react-client
    ports:
      - "3000:80"
    depends_on:
      - node-server
    environment:
      - REACT_APP_API_URL=http://node-server:4000
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE # Specify INSIDE for inter-broker communication
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/kafka/9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kafka-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2182:2181"
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge
